import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1b',
        'on-error-container': '#93000a',
        'on-primary-container': '#92dcc0',
        primary: '#004a38',
        'tertiary-fixed-dim': '#dec1ac',
        'outline-variant': '#bec9c3',
        'primary-fixed-dim': '#8bd5b9',
        'on-surface-variant': '#3f4944',
        'surface-container-highest': '#e2e3e1',
        'hazel-dark': '#5D3A1A',
        error: '#ba1a1a',
        'primary-fixed': '#a7f2d5',
        'inverse-surface': '#2e3130',
        'surface-tint': '#1c6a54',
        'on-primary-fixed': '#002117',
        'on-surface': '#191c1b',
        tertiary: '#503c2c',
        'on-error': '#ffffff',
        'secondary-container': '#feb294',
        'deep-forest': '#042D33',
        'on-primary-fixed-variant': '#00513e',
        'inverse-primary': '#8bd5b9',
        outline: '#6f7974',
        'surface-bright': '#f9faf8',
        'surface-variant': '#e2e3e1',
        'tertiary-fixed': '#fbddc7',
        secondary: '#894f37',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e7e8e6',
        'success-green': '#2E7D32',
        'secondary-fixed': '#ffdbce',
        'surface-dim': '#d9dad8',
        'on-tertiary': '#ffffff',
        background: '#f9faf8',
        'on-secondary-container': '#79422b',
        'surface-container-low': '#f3f4f2',
        'inverse-on-surface': '#f0f1ef',
        'on-primary': '#ffffff',
        surface: '#f9faf8',
        'surface-container': '#edeeec',
        'on-secondary-fixed-variant': '#6d3822',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#28180b',
        'secondary-fixed-dim': '#ffb598',
        'primary-container': '#10634d',
        'almond-cream': '#FAF9F6',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#574333',
        'tertiary-container': '#695342',
        'on-tertiary-container': '#e5c8b3',
        'on-secondary-fixed': '#360f00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        base: '8px',
        'section-gap': '120px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'display-lg': ['"Source Serif 4"', 'serif'],
        'display-lg-mobile': ['"Source Serif 4"', 'serif'],
        'label-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [forms],
};
